name: TBLs Schema Check

on:
  pull_request:

jobs:
  tbls-check:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: start mysql docker
        run: make start opt=-d

      - name: wait for mysql
        run: make wait-for-mysql

      - name: Install tbls
        run: |
          curl -L https://github.com/k1LoW/tbls/releases/download/v1.56.0/tbls_v1.56.0_linux_amd64.tar.gz | tar xvz
          sudo mv tbls /usr/local/bin/tbls

      - name: Run tbls lint
        run: make lint

      - name: Run tbls diff
        run: make diff

